version: "3.9"
services:
  app:
    image: joeyjackson/shape-drawer-app
    ports:
      - "${SHAPE_DRAWER_APP_PORT:-3001}:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE:-shapeDrawer}
      MONGO_USER: ${MONGO_USER:-shapeDrawerAppServer}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
  mongo:
    image: joeyjackson/shape-drawer-mongodb
    restart: always
    environment: 
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE:-shapeDrawer}
      MONGO_USER: ${MONGO_USER:-shapeDrawerAppServer}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

volumes:
  mongo-data:
  mongo-configdb: