name: Build and Push Database Docker Image

on:
  push:
    paths:
      - 'mongo/**'
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Extract metadata for Docker image 
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/shape-drawer-mongodb
          
      - name: Extract metadata for Docker image for raspberry pi flavor
        id: meta-pi
        uses: docker/metadata-action@v6
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/shape-drawer-mongodb
          flavor: prefix=pi,onlatest=true

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build and push primary Docker image
        uses: docker/build-push-action@v7
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true
          context: ./mongo

      - name: Build and push raspberry pi flavor Docker image 
        uses: docker/build-push-action@v7
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-pi.outputs.tags }}
          annotations: ${{ steps.meta-pi.outputs.annotations }}
          labels: ${{ steps.meta-pi.outputs.labels }}
          provenance: true
          sbom: true
          context: ./mongo
          # The latest mongodb version (version 5+) does not run on raspberry pi architecture so an older version must be used
          # The older version also uses the legacy mongo shell instead of mongosh
          build-args:
            - BASE_VERSION=4.4.13
            - MONGO_SHELL=mongo